if vim.g.colors_name then
  vim.cmd("hi clear")
else
end
vim.api.nvim_set_var("colors_name", "modus-operandi-tinted")
vim.api.nvim_set_option_value("termguicolors", true, {})
vim.api.nvim_set_hl(0, "unspecified", {bg = "#000000", fg = "#fbf7f0"})
vim.api.nvim_set_hl(0, "ColorColumn", {bg = "#c9b9b0", fg = "#c9b9b0"})
vim.api.nvim_set_hl(0, "Conceal", {fg = "#193668"})
vim.api.nvim_set_hl(0, "CurSearch", {link = "IncSearch"})
vim.api.nvim_set_hl(0, "Cursor", {bg = "#d00000"})
vim.api.nvim_set_hl(0, "CursorColumn", {bg = "#c9b9b0"})
vim.api.nvim_set_hl(0, "CursorIM", {link = "Cursor"})
vim.api.nvim_set_hl(0, "CursorLine", {bg = "#f1d5d0"})
vim.api.nvim_set_hl(0, "DiffAdd", {bg = "#dcf8d1", fg = "#005000"})
vim.api.nvim_set_hl(0, "DiffChange", {bg = "#ffefbf", fg = "#553d00"})
vim.api.nvim_set_hl(0, "DiffDelete", {bg = "#ffe9e5", fg = "#8f1313"})
vim.api.nvim_set_hl(0, "DiffText", {bg = "#fac090"})
vim.api.nvim_set_hl(0, "Directory", {fg = "#0031a9"})
vim.api.nvim_set_hl(0, "lCursor", {link = "Cursor"})
vim.api.nvim_set_hl(0, "CursorLineFold", {link = "unspecified"})
vim.api.nvim_set_hl(0, "CursorLineNr", {bg = "#c9b9b0", bold = true, fg = "#000000"})
vim.api.nvim_set_hl(0, "CursorLineSign", {link = "SignColumn"})
vim.api.nvim_set_hl(0, "EndOfBuffer", {fg = "#9f9690"})
vim.api.nvim_set_hl(0, "ErrorMsg", {fg = "#7f0000"})
vim.api.nvim_set_hl(0, "FloatBorder", {bg = "#efe9dd", fg = "#9f9690"})
vim.api.nvim_set_hl(0, "FloatTitle", {bg = "#efe9dd", fg = "#595959"})
vim.api.nvim_set_hl(0, "FoldColumn", {link = "unspecified"})
vim.api.nvim_set_hl(0, "Folded", {link = "unspecified"})
vim.api.nvim_set_hl(0, "IncSearch", {bg = "#f3d000", fg = "#000000"})
vim.api.nvim_set_hl(0, "LineNr", {bg = "#efe9dd", fg = "#595959"})
vim.api.nvim_set_hl(0, "LineNrAbove", {bg = "#efe9dd", fg = "#595959"})
vim.api.nvim_set_hl(0, "LineNrBelow", {bg = "#efe9dd", fg = "#595959"})
vim.api.nvim_set_hl(0, "MatchParen", {bg = "#7fdfcf", fg = "#000000"})
vim.api.nvim_set_hl(0, "ModeMsg", {fg = "#002580"})
vim.api.nvim_set_hl(0, "MoreMsg", {fg = "#005f5f"})
vim.api.nvim_set_hl(0, "MsgArea", {fg = "#193668"})
vim.api.nvim_set_hl(0, "MsgSeparator", {link = "unspecified"})
vim.api.nvim_set_hl(0, "NonText", {fg = "#9f9690"})
vim.api.nvim_set_hl(0, "Normal", {bg = "#fbf7f0", fg = "#000000"})
vim.api.nvim_set_hl(0, "NormalFloat", {bg = "#efe9dd", fg = "#000000"})
vim.api.nvim_set_hl(0, "NormalNC", {link = "Normal"})
vim.api.nvim_set_hl(0, "Pmenu", {bg = "#efe9dd", fg = "#000000"})
vim.api.nvim_set_hl(0, "PmenuExtra", {link = "unspecified"})
vim.api.nvim_set_hl(0, "PmenuExtraSel", {link = "unspecified"})
vim.api.nvim_set_hl(0, "PmenuKind", {link = "unspecified"})
vim.api.nvim_set_hl(0, "PmenuKindSel", {link = "unspecified"})
vim.api.nvim_set_hl(0, "PmenuSbar", {bg = "#dfd5cf"})
vim.api.nvim_set_hl(0, "PmenuSel", {bg = "#f0c1cf"})
vim.api.nvim_set_hl(0, "PmenuThumb", {bg = "#193668"})
vim.api.nvim_set_hl(0, "Question", {fg = "#005f5f"})
vim.api.nvim_set_hl(0, "QuickFixLine", {bg = "#f0c1cf", bold = true})
vim.api.nvim_set_hl(0, "Search", {bg = "#a4d5f9", fg = "#000000"})
vim.api.nvim_set_hl(0, "SignColumn", {bg = "#efe9dd"})
vim.api.nvim_set_hl(0, "SnippetTabstop", {link = "unspecified"})
vim.api.nvim_set_hl(0, "SpecialKey", {link = "unspecified"})
vim.api.nvim_set_hl(0, "SpellBad", {sp = "#d00000", undercurl = true})
vim.api.nvim_set_hl(0, "SpellCap", {sp = "#808000", undercurl = true})
vim.api.nvim_set_hl(0, "SpellLocal", {sp = "#008899", undercurl = true})
vim.api.nvim_set_hl(0, "SpellRare", {sp = "#008899", undercurl = true})
vim.api.nvim_set_hl(0, "StatusLine", {bg = "#cab9b2", fg = "#000000"})
vim.api.nvim_set_hl(0, "StatusLineNC", {bg = "#dfd9cf", fg = "#585858"})
vim.api.nvim_set_hl(0, "Substitute", {bg = "#ff8f88", fg = "#000000"})
vim.api.nvim_set_hl(0, "TabLine", {bg = "#c8b8b2"})
vim.api.nvim_set_hl(0, "TabLineFill", {bg = "#e0d4ce"})
vim.api.nvim_set_hl(0, "TabLineSel", {bg = "#fbf7f0", bold = true})
vim.api.nvim_set_hl(0, "TermCursor", {link = "Cursor"})
vim.api.nvim_set_hl(0, "TermCursorNC", {link = "Cursor"})
vim.api.nvim_set_hl(0, "Title", {link = "unspecified"})
vim.api.nvim_set_hl(0, "Visual", {bg = "#c2bcb5", fg = "#000000"})
vim.api.nvim_set_hl(0, "VisualNOS", {bg = "#c2bcb5", fg = "#000000"})
vim.api.nvim_set_hl(0, "WarningMsg", {fg = "#5f0070"})
vim.api.nvim_set_hl(0, "Whitespace", {fg = "#9f9690"})
vim.api.nvim_set_hl(0, "WildMenu", {link = "unspecified"})
vim.api.nvim_set_hl(0, "WinBar", {link = "StatusLine"})
vim.api.nvim_set_hl(0, "WinBarNC", {link = "StatusLineNC"})
vim.api.nvim_set_hl(0, "WinSeparator", {fg = "#c9b9b0"})
vim.api.nvim_set_hl(0, "Boolean", {fg = "#0000b0"})
vim.api.nvim_set_hl(0, "Character", {fg = "#3548cf"})
vim.api.nvim_set_hl(0, "Comment", {fg = "#7f0000"})
vim.api.nvim_set_hl(0, "Conditional", {fg = "#531ab6"})
vim.api.nvim_set_hl(0, "Constant", {fg = "#0000b0"})
vim.api.nvim_set_hl(0, "Debug", {link = "unspecifies"})
vim.api.nvim_set_hl(0, "Define", {fg = "#a0132f"})
vim.api.nvim_set_hl(0, "Delimiter", {fg = "#000000"})
vim.api.nvim_set_hl(0, "Error", {fg = "#a60000"})
vim.api.nvim_set_hl(0, "Exception", {fg = "#531ab6"})
vim.api.nvim_set_hl(0, "Float", {fg = "#000000"})
vim.api.nvim_set_hl(0, "Function", {fg = "#721045"})
vim.api.nvim_set_hl(0, "Identifier", {fg = "#005e8b"})
vim.api.nvim_set_hl(0, "Ignore", {link = "unspecified"})
vim.api.nvim_set_hl(0, "Include", {fg = "#531ab6"})
vim.api.nvim_set_hl(0, "Keyword", {fg = "#531ab6"})
vim.api.nvim_set_hl(0, "Label", {fg = "#531ab6"})
vim.api.nvim_set_hl(0, "Macro", {fg = "#a0132f"})
vim.api.nvim_set_hl(0, "Number", {fg = "#000000"})
vim.api.nvim_set_hl(0, "Operator", {fg = "#000000"})
vim.api.nvim_set_hl(0, "PreCondit", {fg = "#a0132f"})
vim.api.nvim_set_hl(0, "PreProc", {fg = "#a0132f"})
vim.api.nvim_set_hl(0, "Repeat", {fg = "#531ab6"})
vim.api.nvim_set_hl(0, "Special", {fg = "#005f5f"})
vim.api.nvim_set_hl(0, "SpecialChar", {fg = "#721045"})
vim.api.nvim_set_hl(0, "SpecialComment", {fg = "#00663f"})
vim.api.nvim_set_hl(0, "Statement", {fg = "#531ab6"})
vim.api.nvim_set_hl(0, "StorageClass", {fg = "#531ab6"})
vim.api.nvim_set_hl(0, "String", {fg = "#3548cf"})
vim.api.nvim_set_hl(0, "Structure", {fg = "#531ab6"})
vim.api.nvim_set_hl(0, "Tag", {fg = "#721045"})
vim.api.nvim_set_hl(0, "Todo", {fg = "#3548cf"})
vim.api.nvim_set_hl(0, "Type", {fg = "#005f5f"})
vim.api.nvim_set_hl(0, "Typedef", {fg = "#005f5f"})
vim.api.nvim_set_hl(0, "Underlined", {underline = true})
vim.api.nvim_set_hl(0, "@attribute", {link = "PreProc"})
vim.api.nvim_set_hl(0, "@attribute.builtin", {})
vim.api.nvim_set_hl(0, "@boolean", {link = "Boolean"})
vim.api.nvim_set_hl(0, "@character", {link = "Character"})
vim.api.nvim_set_hl(0, "@character.special", {link = "SpecialChar"})
vim.api.nvim_set_hl(0, "@comment", {link = "Comment"})
vim.api.nvim_set_hl(0, "@comment.documentation", {link = "SpecialComment"})
vim.api.nvim_set_hl(0, "@comment.error", {fg = "#a60000"})
vim.api.nvim_set_hl(0, "@comment.note", {fg = "#005f5f"})
vim.api.nvim_set_hl(0, "@comment.todo", {fg = "#005f5f"})
vim.api.nvim_set_hl(0, "@comment.warning", {fg = "#884900"})
vim.api.nvim_set_hl(0, "@constant", {link = "Constant"})
vim.api.nvim_set_hl(0, "@constant.builtin", {link = "Special"})
vim.api.nvim_set_hl(0, "@constant.macro", {link = "Define"})
vim.api.nvim_set_hl(0, "@constructor", {})
vim.api.nvim_set_hl(0, "@diff.delta", {link = "DiffChange"})
vim.api.nvim_set_hl(0, "@diff.minus", {link = "DiffDelete"})
vim.api.nvim_set_hl(0, "@diff.plus", {link = "DiffAdd"})
vim.api.nvim_set_hl(0, "@function", {link = "Function"})
vim.api.nvim_set_hl(0, "@function.builtin", {link = "Special"})
vim.api.nvim_set_hl(0, "@function.call", {link = "@function"})
vim.api.nvim_set_hl(0, "@function.macro", {link = "Macro"})
vim.api.nvim_set_hl(0, "@function.method", {link = "Function"})
vim.api.nvim_set_hl(0, "@function.method.call", {link = "@function.method"})
vim.api.nvim_set_hl(0, "@keyword", {link = "Keyword"})
vim.api.nvim_set_hl(0, "@keyword.conditional", {link = "Conditional"})
vim.api.nvim_set_hl(0, "@keyword.conditional.ternary", {link = "@keyword.conditional"})
vim.api.nvim_set_hl(0, "@keyword.coroutine", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@keyword.debug", {link = "Debug"})
vim.api.nvim_set_hl(0, "@keyword.directive", {link = "PreProc"})
vim.api.nvim_set_hl(0, "@keyword.directive.define", {link = "Define"})
vim.api.nvim_set_hl(0, "@keyword.exception", {link = "Exception"})
vim.api.nvim_set_hl(0, "@keyword.function", {})
vim.api.nvim_set_hl(0, "@keyword.import", {link = "Include"})
vim.api.nvim_set_hl(0, "@keyword.modifier", {})
vim.api.nvim_set_hl(0, "@keyword.operator", {link = "@operator"})
vim.api.nvim_set_hl(0, "@keyword.repeat", {link = "Repeat"})
vim.api.nvim_set_hl(0, "@keyword.return", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@keyword.type", {link = "@type"})
vim.api.nvim_set_hl(0, "@label", {fg = "#193668"})
vim.api.nvim_set_hl(0, "@markup.heading", {bold = true, fg = "#005f5f"})
vim.api.nvim_set_hl(0, "@markup.heading.1", {bold = true, fg = "#000000"})
vim.api.nvim_set_hl(0, "@markup.heading.2", {bold = true, fg = "#624416"})
vim.api.nvim_set_hl(0, "@markup.heading.3", {bold = true, fg = "#193668"})
vim.api.nvim_set_hl(0, "@markup.heading.4", {bold = true, fg = "#721045"})
vim.api.nvim_set_hl(0, "@markup.heading.5", {bold = true, fg = "#2a5045"})
vim.api.nvim_set_hl(0, "@markup.heading.6", {bold = true, fg = "#7f0000"})
vim.api.nvim_set_hl(0, "@markup.italic", {italic = true})
vim.api.nvim_set_hl(0, "@markup.link", {fg = "#595959"})
vim.api.nvim_set_hl(0, "@markup.link.label", {fg = "#3548cf", underline = true})
vim.api.nvim_set_hl(0, "@markup.link.url", {fg = "#193668"})
vim.api.nvim_set_hl(0, "@markup.list", {})
vim.api.nvim_set_hl(0, "@markup.list.checked", {})
vim.api.nvim_set_hl(0, "@markup.list.unchecked", {})
vim.api.nvim_set_hl(0, "@markup.math", {link = "Special"})
vim.api.nvim_set_hl(0, "@markup.quote", {})
vim.api.nvim_set_hl(0, "@markup.raw", {link = "String"})
vim.api.nvim_set_hl(0, "@markup.raw.block", {bg = "#efe9dd"})
vim.api.nvim_set_hl(0, "@markup.raw.markdown_inline", {fg = "#005f5f"})
vim.api.nvim_set_hl(0, "@markup.strikethrough", {strikethrough = true})
vim.api.nvim_set_hl(0, "@markup.strong", {bold = true})
vim.api.nvim_set_hl(0, "@markup.underline", {underline = true})
vim.api.nvim_set_hl(0, "@module", {link = "Include"})
vim.api.nvim_set_hl(0, "@module.builtin", {})
vim.api.nvim_set_hl(0, "@number", {link = "Number"})
vim.api.nvim_set_hl(0, "@number.float", {link = "Float"})
vim.api.nvim_set_hl(0, "@operator", {link = "Operator"})
vim.api.nvim_set_hl(0, "@property", {})
vim.api.nvim_set_hl(0, "@punctuation.bracket", {fg = "#000000"})
vim.api.nvim_set_hl(0, "@punctuation.delimiter", {link = "Delimiter"})
vim.api.nvim_set_hl(0, "@punctuation.special", {})
vim.api.nvim_set_hl(0, "@string", {link = "String"})
vim.api.nvim_set_hl(0, "@string.documentation", {})
vim.api.nvim_set_hl(0, "@string.escape", {})
vim.api.nvim_set_hl(0, "@string.regexp", {})
vim.api.nvim_set_hl(0, "@string.special", {})
vim.api.nvim_set_hl(0, "@string.special.path", {})
vim.api.nvim_set_hl(0, "@string.special.symbol", {})
vim.api.nvim_set_hl(0, "@string.special.url", {})
vim.api.nvim_set_hl(0, "@tag", {link = "Label"})
vim.api.nvim_set_hl(0, "@tag.attribute", {})
vim.api.nvim_set_hl(0, "@tag.builtin", {})
vim.api.nvim_set_hl(0, "@tag.delimiter", {link = "Delimiter"})
vim.api.nvim_set_hl(0, "@type", {link = "Type"})
vim.api.nvim_set_hl(0, "@type.builtin", {})
vim.api.nvim_set_hl(0, "@type.definition", {link = "TypeDef"})
vim.api.nvim_set_hl(0, "@variable", {fg = "#005e8b"})
vim.api.nvim_set_hl(0, "@variable.builtin", {})
vim.api.nvim_set_hl(0, "@variable.member", {link = "Type"})
vim.api.nvim_set_hl(0, "@variable.parameter", {link = "@variable"})
vim.api.nvim_set_hl(0, "@variable.parameter.builtin", {})
vim.api.nvim_set_hl(0, "LspReferenceText", {})
vim.api.nvim_set_hl(0, "LspReferenceRead", {})
vim.api.nvim_set_hl(0, "LspReferenceWrite", {})
vim.api.nvim_set_hl(0, "LspInlayHint", {})
vim.api.nvim_set_hl(0, "LspCodeLens", {})
vim.api.nvim_set_hl(0, "LspCodeLensSeparator", {})
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", {bg = "#f8f0d0", fg = "#884900"})
vim.api.nvim_set_hl(0, "@lsp.type.boolean", {link = "@boolean"})
vim.api.nvim_set_hl(0, "@lsp.type.builtinType", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.comment", {link = "@comment"})
vim.api.nvim_set_hl(0, "@lsp.type.decorator", {link = "@attribute"})
vim.api.nvim_set_hl(0, "@lsp.type.deriveHelper", {link = "@attribute"})
vim.api.nvim_set_hl(0, "@lsp.type.enum", {link = "@type"})
vim.api.nvim_set_hl(0, "@lsp.type.enumMember", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.type.escapeSequence", {link = "@string.escape"})
vim.api.nvim_set_hl(0, "@lsp.type.formatSpecifier", {link = "@markup.list"})
vim.api.nvim_set_hl(0, "@lsp.type.generic", {link = "@variable"})
vim.api.nvim_set_hl(0, "@lsp.type.interface", {link = "unspecified"})
vim.api.nvim_set_hl(0, "@lsp.type.keyword", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@lsp.type.lifetime", {link = "@keyword.storage"})
vim.api.nvim_set_hl(0, "@lsp.type.namespace", {link = "@module"})
vim.api.nvim_set_hl(0, "@lsp.type.number", {link = "@number"})
vim.api.nvim_set_hl(0, "@lsp.type.operator", {link = "@operator"})
vim.api.nvim_set_hl(0, "@lsp.type.parameter", {link = "@variable.parameter"})
vim.api.nvim_set_hl(0, "@lsp.type.property", {link = "@property"})
vim.api.nvim_set_hl(0, "@lsp.type.selfKeyword", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.selfTypeKeyword", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.string", {link = "@string"})
vim.api.nvim_set_hl(0, "@lsp.type.typeAlias", {link = "@type.definition"})
vim.api.nvim_set_hl(0, "@lsp.type.unresolvedReference", {sp = "#a60000", undercurl = true})
vim.api.nvim_set_hl(0, "@lsp.type.variable", {link = "@variable"})
vim.api.nvim_set_hl(0, "@lsp.typemod.class.defaultLibrary", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.enum.defaultLibrary", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.enumMember.defaultLibrary", {link = "@constant.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.async", {link = "@keyword.coroutine"})
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.injected", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@lsp.typemod.macro.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.method.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.injected", {link = "@operator"})
vim.api.nvim_set_hl(0, "@lsp.typemod.string.injected", {link = "@string"})
vim.api.nvim_set_hl(0, "@lsp.typemod.struct.defaultLibrary", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.type.defaultLibrary", {link = "@type"})
vim.api.nvim_set_hl(0, "@lsp.typemod.typeAlias.defaultLibrary", {link = "unspecified"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.callable", {link = "@function"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.injected", {link = "@variable"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.static", {link = "@constant"})
vim.api.nvim_set_hl(0, "DiagnosticDeprecated", {link = "unspecified"})
vim.api.nvim_set_hl(0, "DiagnosticError", {bold = true, fg = "#a60000"})
vim.api.nvim_set_hl(0, "DiagnosticHint", {bold = true, fg = "#005f5f"})
vim.api.nvim_set_hl(0, "DiagnosticInfo", {bold = true, fg = "#005f5f"})
vim.api.nvim_set_hl(0, "DiagnosticUnnecessary", {fg = "#595959"})
vim.api.nvim_set_hl(0, "DiagnosticWarn", {bold = true, fg = "#884900"})
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", {link = "DiagnosticError"})
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", {link = "DiagnosticHint"})
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", {link = "DiagnosticInfo"})
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", {link = "DiagnosticWarn"})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", {sp = "#d00000", undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", {sp = "#008899", undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", {sp = "#008899", undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", {sp = "#808000", undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticFloatingError", {link = "DiagnosticError"})
vim.api.nvim_set_hl(0, "DiagnosticFloatingHint", {link = "DiagnosticHint"})
vim.api.nvim_set_hl(0, "DiagnosticFloatingInfo", {link = "DiagnosticInfo"})
vim.api.nvim_set_hl(0, "DiagnosticFloatingWarn", {link = "DiagnosticWarn"})
vim.api.nvim_set_hl(0, "DiagnosticSignError", {bg = "#ff8f88", fg = "#000000"})
vim.api.nvim_set_hl(0, "DiagnosticSignHint", {bg = "#a4d5f9", fg = "#000000"})
vim.api.nvim_set_hl(0, "DiagnosticSignInfo", {bg = "#a4d5f9", fg = "#000000"})
vim.api.nvim_set_hl(0, "DiagnosticSignWarn", {bg = "#f3d000", fg = "#000000"})
vim.api.nvim_set_hl(0, "BlinkCmpMenu", {bg = "#efe9dd"})
vim.api.nvim_set_hl(0, "BlinkCmpMenuBorder", {fg = "#c9b9b0"})
vim.api.nvim_set_hl(0, "BlinkCmpMenuSelection", {bg = "#f0c1cf", bold = true})
vim.api.nvim_set_hl(0, "BlinkCmpScrollBarThumb", {bg = "#193668"})
vim.api.nvim_set_hl(0, "BlinkCmpScrollBarGutter", {bg = "#dfd5cf"})
vim.api.nvim_set_hl(0, "BlinkCmpLabel", {})
vim.api.nvim_set_hl(0, "BlinkCmpLabelDeprecated", {strikethrough = true})
vim.api.nvim_set_hl(0, "BlinkCmpLabelMatch", {bold = true, fg = "#0031a9"})
vim.api.nvim_set_hl(0, "BlinkCmpLabelDetail", {})
vim.api.nvim_set_hl(0, "BlinkCmpLabelDescription", {})
vim.api.nvim_set_hl(0, "BlinkCmpKind", {})
vim.api.nvim_set_hl(0, "BlinkCmpSource", {})
vim.api.nvim_set_hl(0, "BlinkCmpGhostText", {})
vim.api.nvim_set_hl(0, "BlinkCmpDoc", {})
vim.api.nvim_set_hl(0, "BlinkCmpDocBorder", {})
vim.api.nvim_set_hl(0, "BlinkCmpDocSeparator", {})
vim.api.nvim_set_hl(0, "BlinkCmpDocCursorLine", {})
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelp", {})
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelpBorder", {})
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelpActiveParameter", {})
vim.api.nvim_set_hl(0, "LeapMatch", {link = "IncSearch"})
vim.api.nvim_set_hl(0, "LeapLabel", {bg = "#7feaff", bold = true, fg = "#000000"})
vim.api.nvim_set_hl(0, "LeapBackdrop", {})
vim.api.nvim_set_hl(0, "SnacksPicker", {bg = "#fbf7f0"})
vim.api.nvim_set_hl(0, "SnacksPickerBorder", {bg = "#fbf7f0", fg = "#9f9690"})
vim.api.nvim_set_hl(0, "SnacksPickerListCursorLine", {bg = "#f0c1cf", bold = true})
vim.api.nvim_set_hl(0, "SnacksPickerMatch", {bold = true, fg = "#0031a9"})
vim.api.nvim_set_hl(0, "MiniCursorword", {bg = "#b2e4dc", fg = "#000000"})
vim.api.nvim_set_hl(0, "MiniCursorwordCurrent", {bg = "#b2e4dc", fg = "#000000"})
return vim.api.nvim_set_hl(0, "MiniTrailspace", {bg = "#ff8f88"})
