if vim.g.colors_name then
  vim.cmd("hi clear")
else
end
vim.api.nvim_set_var("colors_name", "modus-vivendi-tinted")
vim.api.nvim_set_option_value("termguicolors", true, {})
vim.api.nvim_set_hl(0, "ColorColumn", {bg = "#4a4f69", fg = "#4a4f69"})
vim.api.nvim_set_hl(0, "Conceal", {fg = "#c6daff"})
vim.api.nvim_set_hl(0, "CurSearch", {link = "IncSearch"})
vim.api.nvim_set_hl(0, "Cursor", {bg = "#ff66ff"})
vim.api.nvim_set_hl(0, "CursorColumn", {bg = "#4a4f69"})
vim.api.nvim_set_hl(0, "CursorIM", {link = "Cursor"})
vim.api.nvim_set_hl(0, "CursorLine", {})
vim.api.nvim_set_hl(0, "DiffAdd", {bg = "#002922", fg = "#a0e0a0"})
vim.api.nvim_set_hl(0, "DiffChange", {bg = "#2a1f00", fg = "#efef80"})
vim.api.nvim_set_hl(0, "DiffDelete", {bg = "#380a19", fg = "#ffbfbf"})
vim.api.nvim_set_hl(0, "DiffText", {bg = "#4a4a00"})
vim.api.nvim_set_hl(0, "Directory", {fg = "#00bcff"})
vim.api.nvim_set_hl(0, "lCursor", {link = "Cursor"})
vim.api.nvim_set_hl(0, "CursorLineFold", {bg = "#1d2235", fg = "#00d3d0"})
vim.api.nvim_set_hl(0, "CursorLineNr", {bg = "#4a4f69", bold = true, fg = "#ffffff"})
vim.api.nvim_set_hl(0, "CursorLineSign", {link = "SignColumn"})
vim.api.nvim_set_hl(0, "EndOfBuffer", {fg = "#61647a"})
vim.api.nvim_set_hl(0, "ErrorMsg", {fg = "#ffa9bf"})
vim.api.nvim_set_hl(0, "FloatBorder", {bg = "#1d2235", fg = "#61647a"})
vim.api.nvim_set_hl(0, "FloatTitle", {bg = "#1d2235", fg = "#989898"})
vim.api.nvim_set_hl(0, "FoldColumn", {bg = "#1d2235", fg = "#00d3d0"})
vim.api.nvim_set_hl(0, "Folded", {bg = "#2b3045", fg = "#989898"})
vim.api.nvim_set_hl(0, "IncSearch", {bg = "#7a6100", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "LineNr", {bg = "#1d2235", fg = "#989898"})
vim.api.nvim_set_hl(0, "LineNrAbove", {bg = "#1d2235", fg = "#989898"})
vim.api.nvim_set_hl(0, "LineNrBelow", {bg = "#1d2235", fg = "#989898"})
vim.api.nvim_set_hl(0, "MatchParen", {bg = "#5f789f", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "ModeMsg", {fg = "#9fefff"})
vim.api.nvim_set_hl(0, "MoreMsg", {fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "MsgArea", {fg = "#c6daff"})
vim.api.nvim_set_hl(0, "NonText", {fg = "#61647a"})
vim.api.nvim_set_hl(0, "Normal", {bg = "#0d0e1c", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "NormalFloat", {bg = "#1d2235", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "NormalNC", {link = "Normal"})
vim.api.nvim_set_hl(0, "Pmenu", {bg = "#1d2235", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "PmenuSbar", {bg = "#2b3045"})
vim.api.nvim_set_hl(0, "PmenuSel", {bg = "#483d8a", bold = true})
vim.api.nvim_set_hl(0, "PmenuThumb", {bg = "#c6daff"})
vim.api.nvim_set_hl(0, "Question", {fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "QuickFixLine", {bg = "#483d8a", bold = true})
vim.api.nvim_set_hl(0, "Search", {bg = "#2266ae", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "SignColumn", {bg = "#1d2235"})
vim.api.nvim_set_hl(0, "SnippetTabstop", {bg = "#45605e", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "SpecialKey", {fg = "#79a8ff"})
vim.api.nvim_set_hl(0, "SpellBad", {sp = "#ff5f5f", undercurl = true})
vim.api.nvim_set_hl(0, "SpellCap", {sp = "#d0bc00", undercurl = true})
vim.api.nvim_set_hl(0, "SpellLocal", {sp = "#00d3d0", undercurl = true})
vim.api.nvim_set_hl(0, "SpellRare", {sp = "#00d3d0", undercurl = true})
vim.api.nvim_set_hl(0, "StatusLine", {bg = "#484d67", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "StatusLineNC", {bg = "#292d48", fg = "#969696"})
vim.api.nvim_set_hl(0, "Substitute", {bg = "#9d1f1f", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "TabLine", {bg = "#4a4f6a"})
vim.api.nvim_set_hl(0, "TabLineFill", {bg = "#2c3045"})
vim.api.nvim_set_hl(0, "TabLineSel", {bg = "#0d0e1c", bold = true})
vim.api.nvim_set_hl(0, "TermCursor", {link = "Cursor"})
vim.api.nvim_set_hl(0, "TermCursorNC", {link = "Cursor"})
vim.api.nvim_set_hl(0, "Title", {fg = "#ffffff"})
vim.api.nvim_set_hl(0, "Visual", {bg = "#555a66", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "VisualNOS", {bg = "#555a66", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "WarningMsg", {fg = "#dfcf43"})
vim.api.nvim_set_hl(0, "Whitespace", {fg = "#61647a"})
vim.api.nvim_set_hl(0, "WildMenu", {fg = "#00bcff"})
vim.api.nvim_set_hl(0, "WinBar", {link = "StatusLine"})
vim.api.nvim_set_hl(0, "WinBarNC", {link = "StatusLineNC"})
vim.api.nvim_set_hl(0, "WinSeparator", {bg = "#1d2235", fg = "#61647a"})
vim.api.nvim_set_hl(0, "Boolean", {fg = "#00bcff"})
vim.api.nvim_set_hl(0, "Character", {fg = "#79a8ff"})
vim.api.nvim_set_hl(0, "Comment", {fg = "#ff9f80"})
vim.api.nvim_set_hl(0, "Conditional", {fg = "#b6a0ff"})
vim.api.nvim_set_hl(0, "Constant", {fg = "#00bcff"})
vim.api.nvim_set_hl(0, "Debug", {fg = "#00bcff"})
vim.api.nvim_set_hl(0, "Define", {fg = "#ff7f86"})
vim.api.nvim_set_hl(0, "Delimiter", {fg = "#ffffff"})
vim.api.nvim_set_hl(0, "Error", {fg = "#ff5f59"})
vim.api.nvim_set_hl(0, "Exception", {fg = "#b6a0ff"})
vim.api.nvim_set_hl(0, "Float", {fg = "#ffffff"})
vim.api.nvim_set_hl(0, "Function", {fg = "#feacd0"})
vim.api.nvim_set_hl(0, "Identifier", {fg = "#00d3d0"})
vim.api.nvim_set_hl(0, "Include", {fg = "#b6a0ff"})
vim.api.nvim_set_hl(0, "Keyword", {fg = "#b6a0ff"})
vim.api.nvim_set_hl(0, "Label", {fg = "#b6a0ff"})
vim.api.nvim_set_hl(0, "Macro", {fg = "#ff7f86"})
vim.api.nvim_set_hl(0, "Number", {fg = "#ffffff"})
vim.api.nvim_set_hl(0, "Operator", {fg = "#ffffff"})
vim.api.nvim_set_hl(0, "PreCondit", {fg = "#ff7f86"})
vim.api.nvim_set_hl(0, "PreProc", {fg = "#ff7f86"})
vim.api.nvim_set_hl(0, "Repeat", {fg = "#b6a0ff"})
vim.api.nvim_set_hl(0, "Special", {fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "SpecialChar", {fg = "#feacd0"})
vim.api.nvim_set_hl(0, "SpecialComment", {fg = "#00c06f"})
vim.api.nvim_set_hl(0, "Statement", {fg = "#b6a0ff"})
vim.api.nvim_set_hl(0, "StorageClass", {fg = "#b6a0ff"})
vim.api.nvim_set_hl(0, "String", {fg = "#79a8ff"})
vim.api.nvim_set_hl(0, "Structure", {fg = "#b6a0ff"})
vim.api.nvim_set_hl(0, "Tag", {fg = "#feacd0"})
vim.api.nvim_set_hl(0, "Todo", {fg = "#79a8ff"})
vim.api.nvim_set_hl(0, "Type", {fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "Typedef", {fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "Underlined", {underline = true})
vim.api.nvim_set_hl(0, "Added", {fg = "#80e080"})
vim.api.nvim_set_hl(0, "Changed", {fg = "#c0b05f"})
vim.api.nvim_set_hl(0, "Removed", {fg = "#ff9095"})
vim.api.nvim_set_hl(0, "@attribute", {link = "PreProc"})
vim.api.nvim_set_hl(0, "@attribute.builtin", {fg = "#f78fe7"})
vim.api.nvim_set_hl(0, "@boolean", {link = "Boolean"})
vim.api.nvim_set_hl(0, "@character", {link = "Character"})
vim.api.nvim_set_hl(0, "@character.special", {link = "SpecialChar"})
vim.api.nvim_set_hl(0, "@comment", {link = "Comment"})
vim.api.nvim_set_hl(0, "@comment.documentation", {link = "@comment"})
vim.api.nvim_set_hl(0, "@comment.error", {})
vim.api.nvim_set_hl(0, "@comment.note", {})
vim.api.nvim_set_hl(0, "@comment.todo", {})
vim.api.nvim_set_hl(0, "@comment.warning", {})
vim.api.nvim_set_hl(0, "@constant", {link = "Constant"})
vim.api.nvim_set_hl(0, "@constant.builtin", {fg = "#f78fe7"})
vim.api.nvim_set_hl(0, "@constant.macro", {link = "Define"})
vim.api.nvim_set_hl(0, "@constructor", {fg = "#ffffff"})
vim.api.nvim_set_hl(0, "@diff.delta", {link = "DiffChange"})
vim.api.nvim_set_hl(0, "@diff.minus", {link = "DiffDelete"})
vim.api.nvim_set_hl(0, "@diff.plus", {link = "DiffAdd"})
vim.api.nvim_set_hl(0, "@function", {link = "Function"})
vim.api.nvim_set_hl(0, "@function.builtin", {fg = "#f78fe7"})
vim.api.nvim_set_hl(0, "@function.call", {link = "@function"})
vim.api.nvim_set_hl(0, "@function.macro", {link = "Macro"})
vim.api.nvim_set_hl(0, "@function.method", {link = "Function"})
vim.api.nvim_set_hl(0, "@function.method.call", {link = "@function.method"})
vim.api.nvim_set_hl(0, "@keyword", {link = "Keyword"})
vim.api.nvim_set_hl(0, "@keyword.conditional", {link = "Conditional"})
vim.api.nvim_set_hl(0, "@keyword.conditional.ternary", {link = "@keyword.conditional"})
vim.api.nvim_set_hl(0, "@keyword.coroutine", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@keyword.debug", {link = "Debug"})
vim.api.nvim_set_hl(0, "@keyword.directive", {link = "PreProc"})
vim.api.nvim_set_hl(0, "@keyword.directive.define", {link = "Define"})
vim.api.nvim_set_hl(0, "@keyword.exception", {link = "Exception"})
vim.api.nvim_set_hl(0, "@keyword.function", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@keyword.import", {link = "Include"})
vim.api.nvim_set_hl(0, "@keyword.modifier", {})
vim.api.nvim_set_hl(0, "@keyword.operator", {link = "@operator"})
vim.api.nvim_set_hl(0, "@keyword.repeat", {link = "Repeat"})
vim.api.nvim_set_hl(0, "@keyword.return", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@keyword.type", {link = "@type"})
vim.api.nvim_set_hl(0, "@label", {fg = "#c6daff"})
vim.api.nvim_set_hl(0, "@markup.heading", {bold = true, fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "@markup.heading.1", {bold = true, fg = "#ffffff"})
vim.api.nvim_set_hl(0, "@markup.heading.2", {bold = true, fg = "#d2b580"})
vim.api.nvim_set_hl(0, "@markup.heading.3", {bold = true, fg = "#82b0ec"})
vim.api.nvim_set_hl(0, "@markup.heading.4", {bold = true, fg = "#feacd0"})
vim.api.nvim_set_hl(0, "@markup.heading.5", {bold = true, fg = "#88ca9f"})
vim.api.nvim_set_hl(0, "@markup.heading.6", {bold = true, fg = "#ff9f80"})
vim.api.nvim_set_hl(0, "@markup.italic", {italic = true})
vim.api.nvim_set_hl(0, "@markup.link", {fg = "#989898"})
vim.api.nvim_set_hl(0, "@markup.link.label", {fg = "#79a8ff", underline = true})
vim.api.nvim_set_hl(0, "@markup.link.url", {fg = "#c6daff"})
vim.api.nvim_set_hl(0, "@markup.list", {})
vim.api.nvim_set_hl(0, "@markup.list.checked", {})
vim.api.nvim_set_hl(0, "@markup.list.unchecked", {})
vim.api.nvim_set_hl(0, "@markup.math", {link = "Special"})
vim.api.nvim_set_hl(0, "@markup.quote", {fg = "#9ac8e0"})
vim.api.nvim_set_hl(0, "@markup.raw", {link = "String"})
vim.api.nvim_set_hl(0, "@markup.raw.block", {bg = "#1d2235"})
vim.api.nvim_set_hl(0, "@markup.raw.markdown_inline", {fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "@markup.strikethrough", {strikethrough = true})
vim.api.nvim_set_hl(0, "@markup.strong", {bold = true})
vim.api.nvim_set_hl(0, "@markup.underline", {underline = true})
vim.api.nvim_set_hl(0, "@module", {link = "Include"})
vim.api.nvim_set_hl(0, "@module.builtin", {fg = "#f78fe7"})
vim.api.nvim_set_hl(0, "@number", {link = "Number"})
vim.api.nvim_set_hl(0, "@number.float", {link = "Float"})
vim.api.nvim_set_hl(0, "@operator", {link = "Operator"})
vim.api.nvim_set_hl(0, "@property", {fg = "#00d3d0"})
vim.api.nvim_set_hl(0, "@punctuation.bracket", {fg = "#ffffff"})
vim.api.nvim_set_hl(0, "@punctuation.delimiter", {link = "Delimiter"})
vim.api.nvim_set_hl(0, "@punctuation.special", {fg = "#ffffff"})
vim.api.nvim_set_hl(0, "@string", {link = "String"})
vim.api.nvim_set_hl(0, "@string.documentation", {fg = "#9ac8e0"})
vim.api.nvim_set_hl(0, "@string.escape", {link = "@string"})
vim.api.nvim_set_hl(0, "@string.regexp", {link = "@string"})
vim.api.nvim_set_hl(0, "@string.special", {link = "Special"})
vim.api.nvim_set_hl(0, "@string.special.path", {link = "Special"})
vim.api.nvim_set_hl(0, "@string.special.symbol", {fg = "#f78fe7"})
vim.api.nvim_set_hl(0, "@string.special.url", {fg = "#c6daff"})
vim.api.nvim_set_hl(0, "@tag", {link = "@function"})
vim.api.nvim_set_hl(0, "@tag.attribute", {link = "@constant"})
vim.api.nvim_set_hl(0, "@tag.builtin", {link = "@tag"})
vim.api.nvim_set_hl(0, "@tag.delimiter", {link = "Delimiter"})
vim.api.nvim_set_hl(0, "@type", {link = "Type"})
vim.api.nvim_set_hl(0, "@type.builtin", {link = "@type"})
vim.api.nvim_set_hl(0, "@type.definition", {link = "TypeDef"})
vim.api.nvim_set_hl(0, "@variable", {fg = "#00d3d0"})
vim.api.nvim_set_hl(0, "@variable.builtin", {fg = "#f78fe7"})
vim.api.nvim_set_hl(0, "@variable.member", {link = "Type"})
vim.api.nvim_set_hl(0, "@variable.parameter", {link = "@variable"})
vim.api.nvim_set_hl(0, "@variable.parameter.builtin", {fg = "#f78fe7"})
vim.api.nvim_set_hl(0, "@lsp.type.boolean", {link = "@boolean"})
vim.api.nvim_set_hl(0, "@lsp.type.builtinType", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.comment", {link = "@comment"})
vim.api.nvim_set_hl(0, "@lsp.type.decorator", {link = "@attribute"})
vim.api.nvim_set_hl(0, "@lsp.type.deriveHelper", {link = "@attribute"})
vim.api.nvim_set_hl(0, "@lsp.type.enum", {link = "@type"})
vim.api.nvim_set_hl(0, "@lsp.type.enumMember", {link = "@constant"})
vim.api.nvim_set_hl(0, "@lsp.type.escapeSequence", {link = "@string.escape"})
vim.api.nvim_set_hl(0, "@lsp.type.formatSpecifier", {link = "@markup.list"})
vim.api.nvim_set_hl(0, "@lsp.type.generic", {link = "@variable"})
vim.api.nvim_set_hl(0, "@lsp.type.interface", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@lsp.type.keyword", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@lsp.type.lifetime", {link = "@keyword.storage"})
vim.api.nvim_set_hl(0, "@lsp.type.namespace", {link = "@module"})
vim.api.nvim_set_hl(0, "@lsp.type.number", {link = "@number"})
vim.api.nvim_set_hl(0, "@lsp.type.operator", {link = "@operator"})
vim.api.nvim_set_hl(0, "@lsp.type.parameter", {link = "@variable.parameter"})
vim.api.nvim_set_hl(0, "@lsp.type.property", {link = "@property"})
vim.api.nvim_set_hl(0, "@lsp.type.selfKeyword", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.selfTypeKeyword", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.type.string", {link = "@string"})
vim.api.nvim_set_hl(0, "@lsp.type.typeAlias", {link = "@type.definition"})
vim.api.nvim_set_hl(0, "@lsp.type.unresolvedReference", {sp = "#ff5f59", undercurl = true})
vim.api.nvim_set_hl(0, "@lsp.type.variable", {link = "@variable"})
vim.api.nvim_set_hl(0, "@lsp.typemod.class.defaultLibrary", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.enum.defaultLibrary", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.enumMember.defaultLibrary", {link = "@constant.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.async", {link = "@keyword.coroutine"})
vim.api.nvim_set_hl(0, "@lsp.typemod.keyword.injected", {link = "@keyword"})
vim.api.nvim_set_hl(0, "@lsp.typemod.macro.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.method.defaultLibrary", {link = "@function.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.operator.injected", {link = "@operator"})
vim.api.nvim_set_hl(0, "@lsp.typemod.string.injected", {link = "@string"})
vim.api.nvim_set_hl(0, "@lsp.typemod.struct.defaultLibrary", {link = "@type.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.type.defaultLibrary", {link = "@type"})
vim.api.nvim_set_hl(0, "@lsp.typemod.typeAlias.defaultLibrary", {link = "@type"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.callable", {link = "@function"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.defaultLibrary", {link = "@variable.builtin"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.injected", {link = "@variable"})
vim.api.nvim_set_hl(0, "@lsp.typemod.variable.static", {link = "@constant"})
vim.api.nvim_set_hl(0, "DiagnosticError", {fg = "#ff5f59"})
vim.api.nvim_set_hl(0, "DiagnosticHint", {fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "DiagnosticInfo", {fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "DiagnosticWarn", {fg = "#fec43f"})
vim.api.nvim_set_hl(0, "DiagnosticUnnecessary", {fg = "#989898"})
vim.api.nvim_set_hl(0, "DiagnosticSignError", {bg = "#1d2235", fg = "#ff5f59"})
vim.api.nvim_set_hl(0, "DiagnosticSignHint", {bg = "#1d2235", fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "DiagnosticSignInfo", {bg = "#1d2235", fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "DiagnosticSignWarn", {bg = "#1d2235", fg = "#fec43f"})
vim.api.nvim_set_hl(0, "DiagnosticLineError", {bg = "#3a0c14"})
vim.api.nvim_set_hl(0, "DiagnosticLineHint", {bg = "#042837"})
vim.api.nvim_set_hl(0, "DiagnosticLineInfo", {bg = "#042837"})
vim.api.nvim_set_hl(0, "DiagnosticLineWarn", {bg = "#381d0f"})
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", {bg = "#3a0c14", fg = "#ff5f59"})
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", {bg = "#042837", fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", {bg = "#042837", fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", {bg = "#381d0f", fg = "#fec43f"})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", {sp = "#ff5f5f", undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", {sp = "#00d3d0", undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", {sp = "#00d3d0", undercurl = true})
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", {sp = "#d0bc00", undercurl = true})
vim.api.nvim_set_hl(0, "BlinkCmpMenu", {bg = "#1d2235", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "BlinkCmpMenuBorder", {bg = "#1d2235", fg = "#4a4f69"})
vim.api.nvim_set_hl(0, "BlinkCmpMenuSelection", {bg = "#483d8a", bold = true})
vim.api.nvim_set_hl(0, "BlinkCmpScrollBarThumb", {bg = "#c6daff"})
vim.api.nvim_set_hl(0, "BlinkCmpScrollBarGutter", {bg = "#2b3045"})
vim.api.nvim_set_hl(0, "BlinkCmpLabel", {fg = "#ffffff"})
vim.api.nvim_set_hl(0, "BlinkCmpLabelDeprecated", {fg = "#c6daff", strikethrough = true})
vim.api.nvim_set_hl(0, "BlinkCmpLabelMatch", {bold = true, fg = "#00bcff"})
vim.api.nvim_set_hl(0, "BlinkCmpLabelDetail", {fg = "#c6daff"})
vim.api.nvim_set_hl(0, "BlinkCmpLabelDescription", {fg = "#c6daff"})
vim.api.nvim_set_hl(0, "BlinkCmpKind", {fg = "#ffffff"})
vim.api.nvim_set_hl(0, "BlinkCmpSource", {fg = "#989898"})
vim.api.nvim_set_hl(0, "BlinkCmpGhostText", {fg = "#989898"})
vim.api.nvim_set_hl(0, "BlinkCmpDoc", {bg = "#1d2235", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "BlinkCmpDocBorder", {bg = "#1d2235", fg = "#61647a"})
vim.api.nvim_set_hl(0, "BlinkCmpDocSeparator", {bg = "#1d2235", fg = "#61647a"})
vim.api.nvim_set_hl(0, "BlinkCmpDocCursorLine", {bg = "#303a6f"})
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelp", {bg = "#1d2235", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelpBorder", {bg = "#1d2235", fg = "#61647a"})
vim.api.nvim_set_hl(0, "BlinkCmpSignatureHelpActiveParameter", {bg = "#381d0f", fg = "#dfaf7a"})
do
  local kinds_1_auto = {Array = "@punctuation.bracket", Boolean = "@boolean", Class = "@type", Color = "Special", Constant = "@constant", Constructor = "@constructor", Enum = "@lsp.type.enum", EnumMember = "@lsp.type.enumMember", Event = "Special", Field = "@variable.member", File = "Normal", Folder = "Directory", Function = "@function", Interface = "@lsp.type.interface", Key = "@variable.member", Keyword = "@lsp.type.keyword", Method = "@function.method", Module = "@module", Namespace = "@module", Null = "@constant.builtin", Number = "@number", Object = "@constant", Operator = "@operator", Package = "@module", Property = "@property", Reference = "@markup.link", Snippet = "Conceal", String = "@string", Struct = "@lsp.type.struct", Text = "@markup", TypeParameter = "@lsp.type.typeParameter", Unit = "@lsp.type.struct", Value = "@string", Variable = "@variable"}
  for kind_2_auto, hl_3_auto in pairs(kinds_1_auto) do
    vim.api.nvim_set_hl(0, ("BlinkCmpKind" .. kind_2_auto), {link = hl_3_auto})
  end
end
vim.api.nvim_set_hl(0, "LeapMatch", {link = "IncSearch"})
vim.api.nvim_set_hl(0, "LeapLabel", {bg = "#0050af", bold = true, fg = "#ffffff"})
vim.api.nvim_set_hl(0, "LeapBackdrop", {})
vim.api.nvim_set_hl(0, "SnacksPicker", {bg = "#0d0e1c"})
vim.api.nvim_set_hl(0, "SnacksPickerBorder", {bg = "#0d0e1c", fg = "#989898"})
vim.api.nvim_set_hl(0, "SnacksPickerDir", {fg = "#ffffff"})
vim.api.nvim_set_hl(0, "SnacksPickerListCursorLine", {bg = "#483d8a", bold = true})
vim.api.nvim_set_hl(0, "SnacksPickerMatch", {bold = true, fg = "#00bcff"})
vim.api.nvim_set_hl(0, "SnacksPickerTitle", {bg = "#0d0e1c", fg = "#989898"})
vim.api.nvim_set_hl(0, "SnacksPickerTotals", {bg = "NONE", fg = "#6ae4b9"})
vim.api.nvim_set_hl(0, "MiniCursorword", {bg = "#45605e", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "MiniCursorwordCurrent", {bg = "#45605e", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "MiniDiffSignAdd", {bg = "#23884f", fg = "#a0e0a0"})
vim.api.nvim_set_hl(0, "MiniDiffSignChange", {bg = "#8f7a30", fg = "#efef80"})
vim.api.nvim_set_hl(0, "MiniDiffSignDelete", {bg = "#b81a26", fg = "#ffbfbf"})
vim.api.nvim_set_hl(0, "MiniIndentscopeSymbol", {fg = "#4a4f69"})
vim.api.nvim_set_hl(0, "MiniSnippetsCurrent", {bg = "#45605e", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "MiniSnippetsCurrentReplace", {bg = "#45605e", fg = "#ffffff"})
vim.api.nvim_set_hl(0, "MiniSnippetsFinal", {sp = "#0d0e1c"})
vim.api.nvim_set_hl(0, "MiniSnippetsUnvisited", {sp = "#0d0e1c"})
vim.api.nvim_set_hl(0, "MiniSnippetsVisited", {sp = "#0d0e1c"})
return vim.api.nvim_set_hl(0, "MiniTrailspace", {bg = "#9d1f1f"})
